### ISSUE TITLE
I can't open developer tools

### ISSUE THREAD

**Issue by kdy1** [Robinfr/electron-react-typescript#17]
I'm on mac.

F12 / Cmd + Option + J neither works.

**Comment by Robinfr** [comment]
As far as I know, it's `Cmd + Option + I` on Mac. Please let me know if that works. Alternatively, you should be able to open it through the application menu I believe.

**Comment by kdy1** [comment]
@Robinfr It worked, thanks! Please feel free to close the issue.

**Comment by Robinfr** [comment]
F12 is a windows only shortcut as far as I know. So I will close this.
