### ISSUE TITLE
Electron 8 compitable for 'require' no found

### ISSUE THREAD

**Issue by PitterL** [Robinfr/electron-react-typescript#22]
Hi, RobinFr:
     Great thanks for your boilerplate!
     When i update the electron to 8.0.0, i found the render app will report error with "request not found" in webpack-dev-server\client. I google and found there should be a 'nodeIntegration' enabled at createWindow() function:
const createWindow = async () => {
    ....
    win = new BrowserWindow({ 
        width: 800, height: 600, 

        // webpack-dev-server\client compatible with 'require'
        webPreferences: {
            nodeIntegration: true
      } 
    });
   ....
}

Best Regards.

**Comment by Robinfr** [comment]
Yes, if you want to use Electron 8, you will have to turn that on, also for testing. However, this template does not use Electron 8, as Spectron does not work that well with Electron 8. In fact, it does not work at all with `nodeIntegration` turned off, and you might not want to turn that on for security reasons.

Thank you for your comment tho, I appreciate you're using the template. I will close this issue tho as it does not apply to the current state of the template 😄
