### ISSUE TITLE
Accessing index.html

### ISSUE THREAD

**Issue by Lagily** [Robinfr/electron-react-typescript#23]
Is it possible to access the index.html and say, for example, add additional headers or CSS imports directly in the index.html?

**Comment by Robinfr** [comment]
Currently, the project is using `HtmlWebpackPlugin` to generate the `index.html` for you. You can decide to remove that plugin and create your own `index.html` file or create a template and pass it to the plugin.

Check out the different options here: https://github.com/jantimon/html-webpack-plugin
