### ISSUE TITLE
White screen after build on Windows

### ISSUE THREAD

**Issue by Vovamzur** [Robinfr/electron-react-typescript#28]
Hello!
I develop in developer mode using
```bash
yarn start-dev
```
but now i want to make .exe on my Windows. I run
```
yarn dist
```
open generated program, but it has only white empty screen. My code is here:
https://github.com/Vovamzur/shit-electron-metro-model
Thanks

**Comment by Robinfr** [comment]
I usually don't give support on specific projects, but you can also run `yarn start` to check whether your project is working.

Anyway, you are doing a bunch of Node stuff in the renderer which wouldn't surprise me if it's breaking your application. Also if you cancel the file open window, you get the same result in dev mode.
