### ISSUE TITLE
seeing error when running npm run start-main-dev

### ISSUE THREAD

**Issue by prabak** [Robinfr/electron-react-typescript#3]
On Windows 10, I was able to run the app successfully. However, I am seeing the following in the log for the `npm run start-main-dev` command. Here is the output:

{ Error: spawn C:\Users\........\dist\7zip-lite\7z.exe ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn C:\\Users\\..........\\dist\\7zip-lite\\7z.exe',
  path: 'C:\\Users\\.............\\dist\\7zip-lite\\7z.exe',
  spawnargs:
   [ 'x',
     'C:\\Users\\.......\\AppData\\Roaming\\Electron\\extensions\\lmhkpmbekcpmknklioeibfkpmmfibljd.crx',
     '-y',
     '-oC:\\Users\\......\\AppData\\Roaming\\Electron\\extensions\\lmhkpmbekcpmknklioeibfkpmmfibljd' ] }

Any idea what this is about?

**Comment by feafarot** [comment]
What was the solution?

**Comment by GuillaumeDesforges** [comment]
A solution would be helpful.

**Comment by Robinfr** [comment]
I've been working on updating all of the depencies. Hopefully that will be released  next week and will solve this problem for you.

**Comment by Robinfr** [comment]
The update has been released, try using that instead and let me know if it helps you out!
