### ISSUE TITLE
Cannot able to import css modules.

### ISSUE THREAD

**Issue by yashvekaria** [Robinfr/electron-react-typescript#31]
I was importing css file in my components. there I am getting this error shown below. 

![Screenshot from 2020-06-17 20-32-00](https://user-images.githubusercontent.com/5152954/84914852-bb994f80-b0d9-11ea-9b43-04087ec4f811.png)

Error
Cannot find module 'renderer/App.module.css' or its corresponding type declarations.ts(2307)

**Comment by Robinfr** [comment]
Hmm that's strange, I haven't seen that problem before. If I have some time I will look into it. Did you make any changes to the webpack configs by any chance?

**Comment by yashvekaria** [comment]
anyways I had done some changes in webpack.renderer.config.js , which resolved my issue finally. Here is the snippet of code, which will allow to create module css.

webpack.base.config.js 
```
resolve: {
        modules: [path.resolve(__dirname, 'src'), 'node_modules'],
        extensions: ['.tsx', '.ts', '.js', '.json', '*.module.css', '.jsx', '.d.ts']
    },
```



webpack.renderer.config.js 
```
{
                test: /\.css$/,
                use: [
                    require.resolve('style-loader'),
                    {
                        loader: require.resolve('css-loader'),
                        options: {
                            importLoaders: 1,
                            modules: true,
                            localIdentName: '[name]__[local]__[hash:base64:5]'
                        },
                    },
                ]
            },
```

**Comment by Robinfr** [comment]
Good that you've resolved it, will close this since this is not supported out of the box without making changes.
