### ISSUE TITLE
Multiple hot-loader recompilation events

### ISSUE THREAD

**Issue by rhyek** [Robinfr/electron-react-typescript#6]
On a newly cloned copy, with npm 6.3.0 running `npm i && npm run start-dev` I get the following behavior:

![image](https://user-images.githubusercontent.com/702922/45002828-69d11500-af98-11e8-8b07-e9df671f99b5.png)

After a bit the events stop and hot reloading works as normal.

After `npm i` there are several modifications done to `package-lock.json`:

```

**Comment by rhyek** [comment]
Btw, if it doesn't do it the first time, close the app and restart it. I should also mention that this is on Ubuntu 18.04.

**Comment by rhyek** [comment]
It is not an issue with the updated packages. I have tried `npm ci` and I get the same behavior.

**Comment by bnsv-jason** [comment]
Not sure what about awesome-typescript-loader caused the issue but switching to ts-loader won't cause the same issue.

**Comment by Kaffiend** [comment]
i'm seeing the same behavior on win10. ill try ts-loader.

**Comment by Robinfr** [comment]
I'm pretty sure this is an issue with awesome-typescript-loader. Maybe related to https://github.com/s-panferov/awesome-typescript-loader/issues/502 ?

Does it keep happening for every change? If the ts-loader works better I'll consider swithcing the project over to that.

**Comment by Robinfr** [comment]
Should be fixed now!
