### ISSUE TITLE
node api fails after pack

### ISSUE THREAD

**Issue by murugaratham** [Robinfr/electron-react-typescript#9]
i am creating a directory within the electron app, which works fine during dev mode. But after packing and trying to mkdir, i'm getting

```
 Error: EACCES: permission denied, mkdir 
```

Is it due to webpack config?

**Comment by Robinfr** [comment]
Seems like a permission error, or a disk error. Did you manage to solve it in the end?

**Comment by Robinfr** [comment]
Closing because no response
